### ISSUE TITLE
Bring back implementation of Alan-FGR to the gitter Lumix room

### ISSUE THREAD

**Issue by hugoam** [Alan-FGR/minBND#2]
The implementation of Alan-FGR on gitter seems to be broken and is not responding anymore
Please fix ASAP

**Comment by troll-kadabra** [comment]
+1 i have quick question

**Comment by Alan-FGR** [comment]
Thanks for the report. I'll reboot Alan-FGR's instance that listens on Gitter asap. :trollface:

**Comment by Alan-FGR** [comment]
@troll-kadabra boi that was creepy :P

**Comment by troll-kadabra** [comment]
xD how is it going in italy @Alan?

**Comment by Alan-FGR** [comment]
It's **not** going... shit happened, which involved problems with permissions to use my family's papers and also the people in the registration office are on vacation so I couldn't get my documents and I'm kinda going back to the starting point. I'm not a double ~~agent~~ *citizen* yet, unfortunately :cry:.

Alan is not the kinda person you'll see sad, but Alan gets a little bit sad when everything goes wrong **:sadtrollface:**.

I didn't give up though (this repo is proof of how stubborn I am :trollface:), but I'll need some time to prepare better, make some decent contacts in Italy, improve my Italian, and I'm also considering going to the north where things seem to work a bit better... and most importantly: apparently I'll need to dump a lot more money on this, and it already reached the 5 figures... what makes you wonder whether your priorities are straight when you're working on a 7 year old laptop :P.

Immigration is so much easier when you're illegal :trollface:

**Comment by troll-kadabra** [comment]
woow, never thought id see you sad. real sry for u bro ❤️️.
are u not staying in italy ?
ps. plz come online on gitter i have question

**Comment by Alan-FGR** [comment]
I can't @troll-kadabra, I'll have to prepare the ground and make sure everything is perfectly sound before I land. I was counting on being able to use my family's papers and didn't even know about vacations and whatnot. Whatever is your question the answer is the same: *use Godot* :trollface:.

For real though, don't worry guys, I'll be online again pretty soon.

**Comment by nem0** [comment]
rewrite in rust when?

**Comment by Alan-FGR** [comment]
Rust wouldn't solve any problem that hasn't already been solved by linked lists and vulkan :trollface:
